name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: |
        cd ./Source
        docker-compose --file docker-compose.yml build
      env:
        TAG: v1
        REGISTRY: lpm10meus2acr


