name: Build and Push Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose --file Source/docker-compose.yml
      env:
        TAG: v1
        REGISTRY: $(acrRegistry)
    - name: Push the Docker images
      run: docker-compose --file Source/docker-compose.yml push


